const ALL_PERMISSIONS = "*";

export const RBAC_PERMISSIONS = Object.freeze({
  AUDIT_READ: "audit.read",
  DASHBOARD_READ: "dashboard.read",
  GALLERY_CREATE: "gallery.create",
  GALLERY_DELETE: "gallery.delete",
  GALLERY_PUBLISH: "gallery.publish",
  GALLERY_READ: "gallery.read",
  GALLERY_UPDATE: "gallery.update",
  MEMBERS_CREATE: "members.create",
  MEMBERS_DELETE: "members.delete",
  MEMBERS_READ: "members.read",
  MEMBERS_UPDATE: "members.update",
  NEWS_CREATE: "news.create",
  NEWS_DELETE: "news.delete",
  NEWS_PUBLISH: "news.publish",
  NEWS_READ: "news.read",
  NEWS_UPDATE: "news.update",
  PHD_PROGRESS_CREATE: "phd_progress.create",
  PHD_PROGRESS_DELETE: "phd_progress.delete",
  PHD_PROGRESS_READ: "phd_progress.read",
  PHD_PROGRESS_UPDATE: "phd_progress.update",
  PROJECTS_CREATE: "projects.create",
  PROJECTS_DELETE: "projects.delete",
  PROJECTS_READ: "projects.read",
  PROJECTS_UPDATE: "projects.update",
  PUBLICATIONS_CREATE: "publications.create",
  PUBLICATIONS_DELETE: "publications.delete",
  PUBLICATIONS_PUBLISH: "publications.publish",
  PUBLICATIONS_READ: "publications.read",
  PUBLICATIONS_UPDATE: "publications.update",
  SETTINGS_READ: "settings.read",
  SETTINGS_UPDATE: "settings.update",
  TEAMS_CREATE: "teams.create",
  TEAMS_DELETE: "teams.delete",
  TEAMS_READ: "teams.read",
  TEAMS_UPDATE: "teams.update",
  USERS_CREATE: "users.create",
  USERS_DELETE: "users.delete",
  USERS_READ: "users.read",
  USERS_RESET_PASSWORD: "users.reset_password",
  USERS_UPDATE: "users.update",
});

const CONTENT_PERMISSIONS = [
  RBAC_PERMISSIONS.DASHBOARD_READ,
  RBAC_PERMISSIONS.TEAMS_READ,
  RBAC_PERMISSIONS.TEAMS_CREATE,
  RBAC_PERMISSIONS.TEAMS_UPDATE,
  RBAC_PERMISSIONS.TEAMS_DELETE,
  RBAC_PERMISSIONS.MEMBERS_READ,
  RBAC_PERMISSIONS.MEMBERS_CREATE,
  RBAC_PERMISSIONS.MEMBERS_UPDATE,
  RBAC_PERMISSIONS.MEMBERS_DELETE,
  RBAC_PERMISSIONS.PROJECTS_READ,
  RBAC_PERMISSIONS.PROJECTS_CREATE,
  RBAC_PERMISSIONS.PROJECTS_UPDATE,
  RBAC_PERMISSIONS.PROJECTS_DELETE,
  RBAC_PERMISSIONS.PUBLICATIONS_READ,
  RBAC_PERMISSIONS.PUBLICATIONS_CREATE,
  RBAC_PERMISSIONS.PUBLICATIONS_UPDATE,
  RBAC_PERMISSIONS.PUBLICATIONS_DELETE,
  RBAC_PERMISSIONS.PUBLICATIONS_PUBLISH,
  RBAC_PERMISSIONS.NEWS_READ,
  RBAC_PERMISSIONS.NEWS_CREATE,
  RBAC_PERMISSIONS.NEWS_UPDATE,
  RBAC_PERMISSIONS.NEWS_DELETE,
  RBAC_PERMISSIONS.NEWS_PUBLISH,
  RBAC_PERMISSIONS.GALLERY_READ,
  RBAC_PERMISSIONS.GALLERY_CREATE,
  RBAC_PERMISSIONS.GALLERY_UPDATE,
  RBAC_PERMISSIONS.GALLERY_DELETE,
  RBAC_PERMISSIONS.GALLERY_PUBLISH,
  RBAC_PERMISSIONS.PHD_PROGRESS_READ,
  RBAC_PERMISSIONS.PHD_PROGRESS_CREATE,
  RBAC_PERMISSIONS.PHD_PROGRESS_UPDATE,
  RBAC_PERMISSIONS.PHD_PROGRESS_DELETE,
];

export const ROLE_PERMISSIONS = Object.freeze({
  super_admin: [ALL_PERMISSIONS],
  content_admin: CONTENT_PERMISSIONS,
  editor: [
    RBAC_PERMISSIONS.DASHBOARD_READ,
    RBAC_PERMISSIONS.TEAMS_READ,
    RBAC_PERMISSIONS.TEAMS_CREATE,
    RBAC_PERMISSIONS.TEAMS_UPDATE,
    RBAC_PERMISSIONS.MEMBERS_READ,
    RBAC_PERMISSIONS.MEMBERS_CREATE,
    RBAC_PERMISSIONS.MEMBERS_UPDATE,
    RBAC_PERMISSIONS.PROJECTS_READ,
    RBAC_PERMISSIONS.PROJECTS_CREATE,
    RBAC_PERMISSIONS.PROJECTS_UPDATE,
    RBAC_PERMISSIONS.PUBLICATIONS_READ,
    RBAC_PERMISSIONS.PUBLICATIONS_CREATE,
    RBAC_PERMISSIONS.PUBLICATIONS_UPDATE,
    RBAC_PERMISSIONS.NEWS_READ,
    RBAC_PERMISSIONS.NEWS_CREATE,
    RBAC_PERMISSIONS.NEWS_UPDATE,
    RBAC_PERMISSIONS.GALLERY_READ,
    RBAC_PERMISSIONS.GALLERY_CREATE,
    RBAC_PERMISSIONS.GALLERY_UPDATE,
    RBAC_PERMISSIONS.PHD_PROGRESS_READ,
    RBAC_PERMISSIONS.PHD_PROGRESS_CREATE,
    RBAC_PERMISSIONS.PHD_PROGRESS_UPDATE,
  ],
});

export function getRolePermissions(role) {
  return ROLE_PERMISSIONS[role] ?? [];
}

export function hasPermission(role, permission) {
  const permissions = getRolePermissions(role);
  return permissions.includes(ALL_PERMISSIONS) || permissions.includes(permission);
}

export function hasAnyPermission(role, permissions) {
  return permissions.some((permission) => hasPermission(role, permission));
}
