export const labInfo = {
  name: "Blida Institution Research Laboratory",
  acronym: " BIRL",
  mission: "Pioneering the frontiers of intelligent systems, bioinformatics, and human-computer interaction through rigorous interdisciplinary research.",
  vision: "A world where science and technology converge to solve humanity's most complex challenges.",
  founded: 2009,
  axes: ["Artificial Intelligence", "Bioinformatics", "Human-Computer Interaction", "Distributed Systems"],
  stats: [
    { label: "Publications", value: "180+" },
    { label: "Active Projects", value: "24" },
    { label: "Researchers", value: "47" },
    { label: "Citations", value: "3.2K" },
  ],
};

export const contactInfo = {
  email: "contact@nexus-lab.edu",
  phone: "+213 (0) 25 11 84 20",
  office: "Research Laboratories Wing, Building C, Second Floor",
  campus: "University Campus of Blida 1",
  city: "Soumaa, Blida 09000, Algeria",
  responseWindow: "Institutional inquiries are typically acknowledged within two working days.",
  officeHours: [
    { label: "Monday to Thursday", value: "08:30 - 16:30" },
    { label: "Friday", value: "08:30 - 12:30" },
  ],
  outreachTracks: [
    {
      title: "General institutional inquiries",
      description:
        "Use the central mailbox for public questions, official requests, and documentation-oriented outreach.",
    },
    {
      title: "Research collaboration",
      description:
        "Prospective collaborators can identify the right team first, then open an institutional introduction through the lab office.",
    },
    {
      title: "Student and supervision interest",
      description:
        "Prospective PhD and research students should reference the relevant axis or team when reaching out.",
    },
  ],
  directions: [
    "Enter through the main university gate and follow the research laboratories signage toward Building C.",
    "The lab coordination office is positioned on the second floor within the shared laboratories wing.",
    "Visitors arriving for scheduled meetings should mention the laboratory office at campus reception.",
  ],
};

export const researchAxes = [
  {
    id: "artificial-intelligence",
    name: "Artificial Intelligence",
    shortLabel: "AI",
    accent: "#1a5c6b",
    summary:
      "Designing learning systems that can reason over complex signals, adapt to changing environments, and remain interpretable enough for high-stakes scientific and societal use.",
    position:
      "This axis frames the lab's work on machine learning foundations, autonomous decision systems, and explainability practices that make advanced models more trustworthy.",
    methods: ["Temporal graph learning", "AutoML pipelines", "Explainability metrics"],
    outcomes: ["Adaptive decision systems", "Transparent model evaluation", "Scientific forecasting tools"],
    teamAcronyms: ["ISAI"],
  },
  {
    id: "bioinformatics",
    name: "Bioinformatics",
    shortLabel: "BIO",
    accent: "#7c4d8a",
    summary:
      "Turning high-dimensional biological data into usable insight through sequence modeling, genomic analysis, and predictive computational pipelines.",
    position:
      "This axis connects computational science with molecular discovery, helping researchers interpret rare disease mechanisms, protein structure behavior, and large-scale omics signals.",
    methods: ["Contrastive embeddings", "Genome data mining", "Protein structure prediction"],
    outcomes: ["Therapeutic discovery support", "Rare disease analysis", "Scalable biological inference"],
    teamAcronyms: ["BIG"],
  },
  {
    id: "human-computer-interaction",
    name: "Human-Computer Interaction",
    shortLabel: "HCI",
    accent: "#b85c38",
    summary:
      "Studying how people perceive, navigate, and trust digital systems while building interfaces that respond to cognition, accessibility, and context.",
    position:
      "This axis keeps the lab's research grounded in human use, ensuring technical systems remain legible, inclusive, and effective in real environments.",
    methods: ["Cognitive load sensing", "Adaptive interface design", "Accessible interaction pipelines"],
    outcomes: ["Inclusive digital experiences", "Human-centered experimentation", "Assistive interaction systems"],
    teamAcronyms: ["HCI"],
  },
  {
    id: "distributed-systems",
    name: "Distributed Systems",
    shortLabel: "SYS",
    accent: "#2d6a4f",
    summary:
      "Engineering resilient compute infrastructures that can coordinate learning, inference, and data exchange across edge, cloud, and collaborative environments.",
    position:
      "This axis provides the systems backbone for scalable research deployment, privacy-aware learning, and fault-tolerant experimentation beyond a single machine or lab setting.",
    methods: ["Federated protocols", "Edge inference runtimes", "Consensus and reliability testing"],
    outcomes: ["Scalable deployment", "Privacy-preserving collaboration", "Fault-tolerant research platforms"],
    teamAcronyms: ["DEC"],
  },
];

export const teams = [
  {
    id: 1,
    slug: "intelligent-systems-ai",
    axisId: "artificial-intelligence",
    name: "Intelligent Systems & AI",
    acronym: "ISAI",
    leader: "Prof. Sarah Chen",
    summary:
      "The ISAI team develops machine learning systems that can model complex environments, support autonomous decision-making, and remain transparent enough for scientific and institutional trust.",
    focus: "Machine learning, deep neural architectures, and reinforcement learning for autonomous decision-making systems.",
    themes: ["Machine Learning", "Graph Intelligence", "Explainable AI", "Autonomous Systems"],
    color: "#1a5c6b",
    members: [
      { name: "Prof. Sarah Chen", role: "Professor", avatar: "SC" },
      { name: "Dr. Marco Bellini", role: "Doctor", avatar: "MB" },
      { name: "Dr. Aisha Ndiaye", role: "Doctor", avatar: "AN" },
      { name: "Lucas Ferreira", role: "PhD Student", avatar: "LF" },
      { name: "Yuna Park", role: "PhD Student", avatar: "YP" },
      { name: "Rami Hassan", role: "PhD Student", avatar: "RH" },
    ],
    projects: ["AutoML Framework", "Neural Graph Networks", "Explainable AI Dashboard"],
    publications: 52,
  },
  {
    id: 2,
    slug: "bioinformatics-genomics",
    axisId: "bioinformatics",
    name: "Bioinformatics & Genomics",
    acronym: "BIG",
    leader: "Prof. James Okafor",
    summary:
      "The BIG team translates genomic and protein-scale data into computational insight, supporting discovery workflows that connect biological complexity with robust predictive modeling.",
    focus: "Computational analysis of biological sequences, protein folding prediction, and genomic data mining.",
    themes: ["Genomics", "Protein Modeling", "Sequence Analysis", "Computational Biology"],
    color: "#7c4d8a",
    members: [
      { name: "Prof. James Okafor", role: "Professor", avatar: "JO" },
      { name: "Dr. Elena Vasquez", role: "Doctor", avatar: "EV" },
      { name: "Ting Wei", role: "PhD Student", avatar: "TW" },
      { name: "Oksana Petrenko", role: "PhD Student", avatar: "OP" },
    ],
    projects: ["Protein Folding Simulator", "Genome Variant Classifier", "Drug Interaction Predictor"],
    publications: 38,
  },
  {
    id: 3,
    slug: "human-computer-interaction",
    axisId: "human-computer-interaction",
    name: "Human-Computer Interaction",
    acronym: "HCI",
    leader: "Prof. Marie Dupont",
    summary:
      "The HCI team studies how people interact with adaptive systems and designs accessible interfaces that respond to cognition, context, and real-world user diversity.",
    focus: "Designing adaptive interfaces, studying cognitive load, and building accessible technologies for diverse users.",
    themes: ["Accessibility", "Adaptive Interfaces", "Cognitive Load", "Assistive Interaction"],
    color: "#b85c38",
    members: [
      { name: "Prof. Marie Dupont", role: "Professor", avatar: "MD" },
      { name: "Dr. Kenji Tanaka", role: "Doctor", avatar: "KT" },
      { name: "Amara Diallo", role: "PhD Student", avatar: "AD" },
      { name: "Filip Novak", role: "PhD Student", avatar: "FN" },
      { name: "Zara Ahmed", role: "PhD Student", avatar: "ZA" },
    ],
    projects: ["Adaptive UI Engine", "Gaze-Based Navigation", "Cognitive Load Monitor"],
    publications: 45,
  },
  {
    id: 4,
    slug: "distributed-edge-computing",
    axisId: "distributed-systems",
    name: "Distributed & Edge Computing",
    acronym: "DEC",
    leader: "Prof. Carlos Rivera",
    summary:
      "The DEC team engineers distributed infrastructures for reliable large-scale learning and inference, with special attention to edge deployment, privacy, and fault tolerance.",
    focus: "Scalable distributed architectures, edge AI deployment, and fault-tolerant consensus protocols.",
    themes: ["Distributed Architectures", "Edge AI", "Federated Learning", "Fault Tolerance"],
    color: "#2d6a4f",
    members: [
      { name: "Prof. Carlos Rivera", role: "Professor", avatar: "CR" },
      { name: "Dr. Nadia Kowalski", role: "Doctor", avatar: "NK" },
      { name: "Chen Jing", role: "PhD Student", avatar: "CJ" },
      { name: "Ibrahim Al-Rashid", role: "PhD Student", avatar: "IA" },
    ],
    projects: ["FedLearn Protocol", "Edge Inference Runtime", "Byzantine Fault Detector"],
    publications: 31,
  },
];

export const projects = [
  {
    id: 1,
    slug: "automl-framework",
    title: "AutoML Framework",
    teamSlug: "intelligent-systems-ai",
    teamTag: "ISAI",
    axisId: "artificial-intelligence",
    lead: "Prof. Sarah Chen",
    status: "Ongoing",
    year: 2025,
    summary:
      "A modular experimentation platform for automated model selection, hyperparameter search, and reproducible benchmarking across the lab's intelligent systems work.",
    themes: ["Machine Learning", "AutoML", "Scientific Forecasting"],
    phdLinked: false,
    milestone:
      "Preparing a shared evaluation layer that will standardize model-comparison workflows across multiple institutional datasets.",
  },
  {
    id: 2,
    slug: "neural-graph-networks",
    title: "Neural Graph Networks",
    teamSlug: "intelligent-systems-ai",
    teamTag: "ISAI",
    axisId: "artificial-intelligence",
    lead: "Dr. Marco Bellini",
    status: "Ongoing",
    year: 2024,
    summary:
      "A project focused on graph-native architectures for dynamic environments, with emphasis on temporal reasoning, sparse connectivity, and explainable predictions.",
    themes: ["Graph Intelligence", "Temporal Graph Learning", "Explainable AI"],
    phdLinked: true,
    milestone:
      "Directly connected to doctoral work on reinforcement and graph reasoning methods within the ISAI roster.",
  },
  {
    id: 3,
    slug: "explainable-ai-dashboard",
    title: "Explainable AI Dashboard",
    teamSlug: "intelligent-systems-ai",
    teamTag: "ISAI",
    axisId: "artificial-intelligence",
    lead: "Dr. Aisha Ndiaye",
    status: "Completed",
    year: 2023,
    summary:
      "An interpretability environment that turns black-box model diagnostics into readable institutional evidence for researchers, reviewers, and partners.",
    themes: ["Explainable AI", "Model Evaluation", "Decision Support"],
    phdLinked: false,
    milestone:
      "Completed a first public-ready layer for transparent reporting across high-stakes experimental models.",
  },
  {
    id: 4,
    slug: "protein-folding-simulator",
    title: "Protein Folding Simulator",
    teamSlug: "bioinformatics-genomics",
    teamTag: "BIG",
    axisId: "bioinformatics",
    lead: "Prof. James Okafor",
    status: "Ongoing",
    year: 2025,
    summary:
      "A computational modeling environment for predicting protein structure behavior and comparing contrastive sequence embeddings against baseline biological pipelines.",
    themes: ["Protein Modeling", "Sequence Analysis", "Computational Biology"],
    phdLinked: false,
    milestone:
      "Expanding benchmark coverage to rare protein families while improving simulation traceability for peer review.",
  },
  {
    id: 5,
    slug: "genome-variant-classifier",
    title: "Genome Variant Classifier",
    teamSlug: "bioinformatics-genomics",
    teamTag: "BIG",
    axisId: "bioinformatics",
    lead: "Dr. Elena Vasquez",
    status: "Ongoing",
    year: 2024,
    summary:
      "A classification pipeline for clinically relevant genome variants that combines sequence embeddings, curated feature extraction, and validation against lab reference sets.",
    themes: ["Genomics", "Rare Disease Analysis", "Computational Biology"],
    phdLinked: true,
    milestone:
      "Supports doctoral progress on biomarker interpretation and predictive genomic triage workflows.",
  },
  {
    id: 6,
    slug: "drug-interaction-predictor",
    title: "Drug Interaction Predictor",
    teamSlug: "bioinformatics-genomics",
    teamTag: "BIG",
    axisId: "bioinformatics",
    lead: "Ting Wei",
    status: "Planned",
    year: 2026,
    summary:
      "A next-phase discovery project aimed at detecting compound interaction patterns across heterogeneous biological datasets and therapeutic target graphs.",
    themes: ["Drug Discovery", "Predictive Biology", "Data Mining"],
    phdLinked: true,
    milestone:
      "Now in planning, with doctoral framing around benchmark design and data-governance constraints.",
  },
  {
    id: 7,
    slug: "adaptive-ui-engine",
    title: "Adaptive UI Engine",
    teamSlug: "human-computer-interaction",
    teamTag: "HCI",
    axisId: "human-computer-interaction",
    lead: "Prof. Marie Dupont",
    status: "Ongoing",
    year: 2025,
    summary:
      "An interface engine that adjusts presentation density, guidance, and interaction pathways in response to user context, load, and accessibility needs.",
    themes: ["Adaptive Interfaces", "Accessibility", "Human-Centered Experimentation"],
    phdLinked: false,
    milestone:
      "Running iterative validation across multiple interface patterns to improve readability and completion rates.",
  },
  {
    id: 8,
    slug: "gaze-based-navigation",
    title: "Gaze-Based Navigation",
    teamSlug: "human-computer-interaction",
    teamTag: "HCI",
    axisId: "human-computer-interaction",
    lead: "Dr. Kenji Tanaka",
    status: "Completed",
    year: 2023,
    summary:
      "A mobility-focused interaction project exploring gaze tracking for precise navigation, dwell-based selection, and assistive interface control.",
    themes: ["Assistive Interaction", "Accessibility", "Eye Tracking"],
    phdLinked: false,
    milestone:
      "Completed with validated accessibility findings that now inform follow-up HCI interface work.",
  },
  {
    id: 9,
    slug: "cognitive-load-monitor",
    title: "Cognitive Load Monitor",
    teamSlug: "human-computer-interaction",
    teamTag: "HCI",
    axisId: "human-computer-interaction",
    lead: "Amara Diallo",
    status: "Ongoing",
    year: 2024,
    summary:
      "A sensing and adaptation pipeline that estimates cognitive effort in real time and helps interfaces reduce complexity when user strain increases.",
    themes: ["Cognitive Load", "Adaptive Interfaces", "Accessible Interaction"],
    phdLinked: true,
    milestone:
      "Acts as a doctoral research bridge between interface adaptation and measurable human-response signals.",
  },
  {
    id: 10,
    slug: "fedlearn-protocol",
    title: "FedLearn Protocol",
    teamSlug: "distributed-edge-computing",
    teamTag: "DEC",
    axisId: "distributed-systems",
    lead: "Prof. Carlos Rivera",
    status: "Ongoing",
    year: 2025,
    summary:
      "A federated coordination protocol for collaborative learning across institutional boundaries with attention to resilience, privacy, and deployment realism.",
    themes: ["Federated Learning", "Privacy-Preserving Collaboration", "Distributed Architectures"],
    phdLinked: false,
    milestone:
      "Current work focuses on protocol stability and deployment patterns for multi-site training environments.",
  },
  {
    id: 11,
    slug: "edge-inference-runtime",
    title: "Edge Inference Runtime",
    teamSlug: "distributed-edge-computing",
    teamTag: "DEC",
    axisId: "distributed-systems",
    lead: "Dr. Nadia Kowalski",
    status: "Ongoing",
    year: 2024,
    summary:
      "A runtime environment for deploying machine inference at the edge with bounded latency, observability hooks, and privacy-aware synchronization.",
    themes: ["Edge AI", "Scalable Deployment", "Fault Tolerance"],
    phdLinked: true,
    milestone:
      "Supports doctoral experiments on privacy-aware deployment and resilient coordination between edge nodes.",
  },
  {
    id: 12,
    slug: "byzantine-fault-detector",
    title: "Byzantine Fault Detector",
    teamSlug: "distributed-edge-computing",
    teamTag: "DEC",
    axisId: "distributed-systems",
    lead: "Chen Jing",
    status: "Completed",
    year: 2022,
    summary:
      "A reliability-testing project that studied adversarial and faulty behavior in collaborative distributed environments and proposed lightweight detection strategies.",
    themes: ["Fault Tolerance", "Consensus", "Reliability Testing"],
    phdLinked: false,
    milestone:
      "Completed baseline detection experiments that now inform the protocol layer of newer DEC initiatives.",
  },
];

export const publications = [
  {
    id: 1,
    slug: "transformers-for-temporal-graph-learning",
    title: "Transformers for Temporal Graph Learning: A Unified Framework",
    authors: ["S. Chen", "L. Ferreira", "M. Bellini"],
    entryType: "inproceedings",
    publisher: "NeurIPS",
    journal: "NeurIPS 2024",
    year: 2024,
    teamTag: "ISAI",
    themes: ["Machine Learning", "Graph Intelligence", "Temporal Graph Learning"],
    doi: "10.48550/arXiv.2401.10231",
    pdfLink: "#",
    abstract: "We propose a novel unified framework for applying transformer architectures to temporal graphs, achieving state-of-the-art results across 12 benchmarks.",
    citations: 143,
  },
  {
    id: 2,
    slug: "protein-folding-prediction-via-contrastive-sequence-embeddings",
    title: "Protein Folding Prediction via Contrastive Sequence Embeddings",
    authors: ["J. Okafor", "E. Vasquez", "T. Wei"],
    entryType: "article",
    publisher: "Nature Computational Science",
    journal: "Nature Computational Science",
    year: 2024,
    teamTag: "BIG",
    themes: ["Protein Modeling", "Sequence Analysis", "Computational Biology"],
    doi: "10.1038/s43588-024-00618-2",
    pdfLink: "#",
    abstract: "A contrastive learning approach for generating robust protein sequence embeddings, outperforming ESMFold on rare protein families.",
    citations: 89,
  },
  {
    id: 3,
    slug: "cognitive-load-estimation-in-adaptive-user-interfaces",
    title: "Cognitive Load Estimation in Adaptive User Interfaces",
    authors: ["M. Dupont", "K. Tanaka", "A. Diallo"],
    entryType: "inproceedings",
    publisher: "ACM CHI",
    journal: "ACM CHI 2024",
    year: 2024,
    teamTag: "HCI",
    themes: ["Cognitive Load", "Adaptive Interfaces", "Accessible Interaction"],
    doi: "10.1145/3613904.3642217",
    pdfLink: "#",
    abstract: "Real-time cognitive load estimation using physiological signals to drive adaptive UI complexity reduction, improving task completion by 31%.",
    citations: 67,
  },
  {
    id: 4,
    slug: "fedgraph-federated-learning-over-heterogeneous-graph-networks",
    title: "FedGraph: Federated Learning over Heterogeneous Graph Networks",
    authors: ["C. Rivera", "N. Kowalski", "C. Jing"],
    entryType: "inproceedings",
    publisher: "IEEE ICDCS",
    journal: "IEEE ICDCS 2023",
    year: 2023,
    teamTag: "DEC",
    themes: ["Federated Learning", "Privacy-Preserving Collaboration", "Distributed Architectures"],
    doi: "10.1109/ICDCS57875.2023.00112",
    pdfLink: "#",
    abstract: "A federated learning protocol specifically designed for heterogeneous graph data, preserving privacy while maintaining model accuracy.",
    citations: 201,
  },
  {
    id: 5,
    slug: "explainability-metrics-for-black-box-neural-models",
    title: "Explainability Metrics for Black-Box Neural Models",
    authors: ["S. Chen", "A. Ndiaye", "Y. Park"],
    entryType: "inproceedings",
    publisher: "ICML",
    journal: "ICML 2023",
    year: 2023,
    teamTag: "ISAI",
    themes: ["Explainable AI", "Model Evaluation", "Decision Support"],
    doi: "10.48550/arXiv.2305.08721",
    pdfLink: "#",
    abstract: "We introduce a suite of quantitative explainability metrics to evaluate post-hoc explanation methods across diverse neural architectures.",
    citations: 174,
  },
  {
    id: 6,
    slug: "gaze-driven-interaction-for-mobility-impaired-users",
    title: "Gaze-Driven Interaction for Mobility-Impaired Users",
    authors: ["M. Dupont", "F. Novak", "Z. Ahmed"],
    entryType: "inproceedings",
    publisher: "ACM ASSETS",
    journal: "ASSETS 2023",
    year: 2023,
    teamTag: "HCI",
    themes: ["Assistive Interaction", "Accessibility", "Eye Tracking"],
    doi: "10.1145/3597638.3608414",
    pdfLink: "#",
    abstract: "A novel gaze-tracking pipeline enabling precise cursor control with sub-pixel accuracy, validated with 45 mobility-impaired participants.",
    citations: 52,
  },
];

export const news = [
  {
    id: 1,
    slug: "nexus-lab-wins-best-paper-award-at-neurips-2024",
    headline: "Nexus Lab wins Best Paper Award at NeurIPS 2024",
    dateIso: "2024-12-12",
    date: "December 12, 2024",
    category: "Award",
    teamTags: ["ISAI"],
    image: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=600&q=80",
    excerpt: "The ISAI team's paper on Transformers for Temporal Graph Learning received the prestigious Best Paper Award, recognizing its outstanding contribution to the field.",
    body: [
      "The award recognizes the lab's work on temporal graph learning as one of the most significant contributions presented at this year's conference. Reviewers highlighted the paper's technical clarity, strong benchmark performance, and the practical value of its unified framework for modeling dynamic graph systems.",
      "For the lab, the distinction is more than a one-off prize. It signals that the Intelligent Systems and AI team is producing work that resonates internationally while still fitting into the institution's broader goal of credible, high-impact research.",
      "The recognition also reinforces the value of maintaining a public platform where awards, papers, and team identity are connected. Visitors should be able to move naturally from the news headline into the publication record and the team behind it.",
    ],
  },
  {
    id: 2,
    slug: "eur-2-4m-horizon-europe-grant-awarded-to-big-team",
    headline: "EUR 2.4M Horizon Europe Grant Awarded to BIG Team",
    dateIso: "2024-11-03",
    date: "November 3, 2024",
    category: "Funding",
    teamTags: ["BIG"],
    image: "https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=600&q=80",
    excerpt: "The Bioinformatics & Genomics team secures a landmark European research grant to advance protein structure prediction for rare disease therapies.",
    body: [
      "The new Horizon Europe grant gives the Bioinformatics and Genomics team a major platform for advancing its work on protein structure prediction and rare disease analysis. The funding supports both computational infrastructure and the collaborative scientific workflows needed to move from experimental modeling to validated biomedical insight.",
      "The project will strengthen the lab's visibility within European research networks while also creating a more durable institutional foundation for long-term bioinformatics work. It brings together genome data interpretation, predictive modeling, and therapeutic discovery support under one funded program.",
      "On the public site, stories like this matter because they show the lab as an active research institution with external trust, real partnerships, and the capacity to translate technical work into sustained scientific programs.",
    ],
  },
  {
    id: 3,
    slug: "nexus-lab-opens-new-collaboration-with-mit-media-lab",
    headline: "Nexus Lab Opens New Collaboration with MIT Media Lab",
    dateIso: "2024-10-18",
    date: "October 18, 2024",
    category: "Partnership",
    teamTags: ["HCI"],
    image: "https://images.unsplash.com/photo-1564325724739-bae0bd08762c?w=600&q=80",
    excerpt: "NEXUS and MIT Media Lab formalize a joint research initiative focused on accessible computing interfaces for neurodiverse populations.",
    body: [
      "The new collaboration expands the Human-Computer Interaction team's research network into a highly visible international partnership. Both groups will focus on accessible computing systems that better serve neurodiverse users through adaptive interface design and more responsive interaction models.",
      "The partnership is expected to support shared workshops, co-authored outputs, and comparative evaluation across different research environments. It also adds a strong public-facing signal that the lab is operating inside a broader ecosystem of international collaboration.",
      "For prospective students and partners, this story helps explain how the lab's HCI work connects local research priorities to global conversations about accessibility, cognition, and inclusive design.",
    ],
  },
  {
    id: 4,
    slug: "phd-defense-rami-hassan-earns-doctorate-with-honours",
    headline: "PhD Defense: Rami Hassan Earns Doctorate with Honours",
    dateIso: "2024-09-29",
    date: "September 29, 2024",
    category: "Milestone",
    teamTags: ["ISAI"],
    image: "https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?w=600&q=80",
    excerpt: "Rami Hassan successfully defended his dissertation on reinforcement learning for autonomous robotics, receiving honours from the evaluation committee.",
    body: [
      "Rami Hassan's successful defense marks an important milestone for both the researcher and the Intelligent Systems and AI team. His dissertation on reinforcement learning for autonomous robotics contributes to the lab's longer-term work on decision-making systems that can adapt under real-world constraints.",
      "The defense also demonstrates the value of making doctoral progress legible on the public platform. Academic milestones are part of the lab's visible output, and they help connect publications, supervision, and project activity to individual research journeys.",
      "Stories like this can later connect naturally to the dedicated PhD progress tracker, giving the public site a fuller picture of how advanced research develops across time rather than appearing only as isolated final outputs.",
    ],
  },
];

export const gallery = [
  {
    id: 1,
    slug: "neurips-award-stage",
    title: "NeurIPS Award Moment",
    caption: "The ISAI team receives formal recognition after the best paper announcement, marking one of the lab's strongest recent international visibility signals.",
    category: "Conference",
    dateIso: "2024-12-12",
    date: "December 12, 2024",
    teamTag: "ISAI",
    image: "https://images.unsplash.com/photo-1511578314322-379afb476865?w=1200&q=80",
  },
  {
    id: 2,
    slug: "genomics-lab-bench-session",
    title: "Genomics Lab Bench Session",
    caption: "A capture from a BIG research session where computational workflows and biological interpretation move side by side in the same working environment.",
    category: "Lab Life",
    dateIso: "2024-11-18",
    date: "November 18, 2024",
    teamTag: "BIG",
    image: "https://images.unsplash.com/photo-1532187643603-ba119ca4109e?w=1200&q=80",
  },
  {
    id: 3,
    slug: "accessible-interface-workshop",
    title: "Accessible Interface Workshop",
    caption: "The HCI team hosts an internal workshop on adaptive interface patterns, eye tracking, and inclusive interaction design for diverse user groups.",
    category: "Workshop",
    dateIso: "2024-10-21",
    date: "October 21, 2024",
    teamTag: "HCI",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=1200&q=80",
  },
  {
    id: 4,
    slug: "distributed-systems-control-room",
    title: "Distributed Systems Control Room",
    caption: "A monitoring wall used during DEC reliability tests, where edge runtime behavior and distributed coordination signals are reviewed in real time.",
    category: "Infrastructure",
    dateIso: "2024-09-14",
    date: "September 14, 2024",
    teamTag: "DEC",
    image: "https://images.unsplash.com/photo-1516321165247-4aa89a48be28?w=1200&q=80",
  },
  {
    id: 5,
    slug: "doctoral-defense-day",
    title: "Doctoral Defense Day",
    caption: "A formal university moment marking the successful defense of a doctoral dissertation connected to the lab's autonomous systems research line.",
    category: "Milestone",
    dateIso: "2024-09-29",
    date: "September 29, 2024",
    teamTag: "ISAI",
    image: "https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?w=1200&q=80",
  },
  {
    id: 6,
    slug: "bioinformatics-data-review",
    title: "Bioinformatics Data Review",
    caption: "Researchers compare outputs from sequence models and genomic datasets during a focused BIG review session on rare disease workflows.",
    category: "Research Session",
    dateIso: "2024-08-11",
    date: "August 11, 2024",
    teamTag: "BIG",
    image: "https://images.unsplash.com/photo-1518152006812-edab29b069ac?w=1200&q=80",
  },
  {
    id: 7,
    slug: "cross-team-methods-roundtable",
    title: "Cross-Team Methods Roundtable",
    caption: "An internal roundtable where teams compare methods, datasets, and publication priorities across the lab's four scientific axes.",
    category: "Institutional",
    dateIso: "2024-07-03",
    date: "July 3, 2024",
    teamTag: "",
    image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=1200&q=80",
  },
  {
    id: 8,
    slug: "edge-runtime-demo",
    title: "Edge Runtime Demo",
    caption: "A demonstration of the DEC edge inference environment during a technical review focused on observability, latency, and deployment resilience.",
    category: "Demo",
    dateIso: "2024-06-19",
    date: "June 19, 2024",
    teamTag: "DEC",
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200&q=80",
  },
  {
    id: 9,
    slug: "adaptive-interface-testing",
    title: "Adaptive Interface Testing",
    caption: "A hands-on HCI evaluation session examining how interface density and guidance cues shift under different cognitive load conditions.",
    category: "Field Study",
    dateIso: "2024-05-24",
    date: "May 24, 2024",
    teamTag: "HCI",
    image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=1200&q=80",
  },
  {
    id: 10,
    slug: "grant-kickoff-briefing",
    title: "Grant Kickoff Briefing",
    caption: "An institutional briefing held after the Horizon Europe award, setting priorities for the BIG program's first implementation phase.",
    category: "Institutional",
    dateIso: "2024-04-12",
    date: "April 12, 2024",
    teamTag: "BIG",
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=1200&q=80",
  },
];

export const faculty = [
  { name: "Prof. Sarah Chen", title: "Professor & Lab Director", team: "ISAI", expertise: "Deep Learning, AutoML", avatar: "SC" },
  { name: "Prof. James Okafor", title: "Professor", team: "BIG", expertise: "Genomics, Bioinformatics", avatar: "JO" },
  { name: "Prof. Marie Dupont", title: "Associate Professor", team: "HCI", expertise: "Adaptive UI, Accessibility", avatar: "MD" },
  { name: "Prof. Carlos Rivera", title: "Associate Professor", team: "DEC", expertise: "Distributed Systems, Edge AI", avatar: "CR" },
  { name: "Dr. Marco Bellini", title: "Researcher", team: "ISAI", expertise: "Graph Neural Networks", avatar: "MB" },
  { name: "Dr. Aisha Ndiaye", title: "Researcher", team: "ISAI", expertise: "Explainable AI", avatar: "AN" },
  { name: "Dr. Elena Vasquez", title: "Researcher", team: "BIG", expertise: "Protein Folding, ML", avatar: "EV" },
  { name: "Dr. Kenji Tanaka", title: "Researcher", team: "HCI", expertise: "Cognitive Science, Eye Tracking", avatar: "KT" },
  { name: "Dr. Nadia Kowalski", title: "Researcher", team: "DEC", expertise: "Federated Learning, Privacy", avatar: "NK" },
];
